name: First mirror from tclone to rtos work

on:
  workflow_call:
    inputs:
      source-repo:
        required: true
        type: string
      target-repo:
        required: true
        type: string
      source-repo-name:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  synchronize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    

      - name: Set Github Credentials
        run: |
          git config --global user.email "ghost8658@gmail.com"
          git config --global user.name "ghost8658"



      - name: Set Git Credentials
        if: github.repository == 'ghost8658private/tsdk'
        run: |
          git config --global user.email "bbbeeeaaabbb9@gmail.com"
          git config --global user.name "ghost8658private"


      - name: Push to target repo
        run: |
          git clone ${{ inputs.source-repo }}
          cd ${{ inputs.source-repo-name }}
          git remote -v
          # git remote remove origin
          git remote set-url --push origin ${{ inputs.target-repo }}
          git push -f --all ${{ inputs.target-repo }}