name: Mirror Branch

on:
  push:
    branches:
      - power

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Sync changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # Clone the destination repository
          git clone https://github.com/ghost8658private/fourth.git

          # Navigate into the destination repository directory
          cd fourth

          # Checkout the branch
          git checkout power

          # Pull changes from the source repository
          git pull https://github.com/ghost8658private/ttesting.git power

          # Push changes to the mirror branch
          git push origin power

      - name: Cleanup
        run: |
          cd ..
          rm -rf destination-repo
