name: Mirror Branch

on:
  workflow_call:
    inputs:
      source_repo:
        required: true
        type: string
      source_branch:
        required: true
        type: string
      destination_branch:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true


jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: mirror main
        uses: repo-sync/github-sync@v2
        with:
          source_repo: ${{ inputs.source_repo }}
          source_branch: ${{ inputs.source_branch }}
          destination_branch: ${{ inputs.destination_branch }}
          github_token: ${{ secrets.PAT_TOKEN }}