name: Clone and Push Workflow

on:
  push:
    branches:
      - main 

env:
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
  DEST_REPO_URL: "https://github.com/ghost8658private/trtos.git"

jobs:
  clone_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2 

    - name: Configure Git
      run: |
        git config user.name "${GIT_USERNAME}"
        git config user.email "${GIT_USERNAME}@users.noreply.github.com"
        git config credential.helper store <<<"${GIT_PASSWORD}"
        git config --global core.askpass /usr/share/doc/git/contrib/credential/gnome-credential-store/git-credential-gnome-keyring

    - name: Clone destination repository
      run: git clone "${DEST_REPO_URL}" destination-repo
        
    - name: Copy source repository files to destination repository
      run: cp -r ${{ github.workspace }}/* destination-repo/
        
    - name: Move to destination repository directory
      run: cd destination-repo
        
    - name: Configure Git for destination repository
      run: |
        git config user.name "${GIT_USERNAME}"
        git config user.email "${GIT_USERNAME}@users.noreply.github.com"
        
    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Sync with source repository"
        git push origin main
