name: Mirror Branch to Public Repo

on:
  workflow_call:
    inputs:
      source-branch:
          required: true
          type: string
      target-repo-name:
        description: 'Name of the target repository'
        required: true
        type: string
      target-repo-url:
        description: 'URL of the target repository'
        required: true
        type: string
      base-branch:
        required: true
        type: string
      main-sha:
        type: string
      tmo-main-sha:
        type: string
      source-repo-name:
        required: true
        type: string
    secrets:
      PAT_TOKEN:
        required: true

jobs:
  Mirror_to_public:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ inputs.source-branch }}

      - name: Push to target repository
        run: |
          # Configure git
          git config --global user.email "ghost8658@gmail.com"
          git config --global user.name "ghost8658"
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com" > ~/.git-credentials
          
          # Clone target repository
          cd ..
          git clone "${{ inputs.target-repo-url }}" ${{ inputs.target-repo-name }}
          cd ${{ inputs.target-repo-name }}    
          git remote set-url origin ${{ inputs.target-repo-url }}
          git push --set-upstream ${{ inputs.source-branch }}

      - name: Cleanup
        run: |
          rm -rf ${{ inputs.target-repo-name }}