name: Mirror Branch
on:
  push:
    branches:
      - power
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'ghost8658private/devopsworkflows'
          ref: power
          token: ${{ secrets.PAT_TOKEN }}
      - uses: actions/checkout@v2
        with:
          repository: 'ghost8658private/ttesting'
          ref: power
          token: ${{ secrets.PAT_TOKEN }}
      - name: Mirror branch
        run: |
          git fetch --all
          git merge --allow-unrelated-histories ghost8658private/devopsworkflows/power ghost8658private/ttesting/power