name: Mirror Main Branch and Create PR

on:
  push:
    branches:
      - main

jobs:
  mirror-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Clone destination repository
        run: |
          git config --global url.https://${{ secrets.GITHUB_TOKEN}}@github.com/.insteadOf https://github.com/
          git config --global user.name "Ghost8658"
          git config --global user.email "140547947+Ghost8658@users.noreply.github.com"

          git clone --branch main --depth 1 --quiet https://github.com/ghost8658private/trtos.git destination-repo


      - name: Push changes to destination repository
        run: |
          cd destination-repo

          # Ensure the target branch exists in the destination repository
          git checkout -B main

          # Fetch changes from source repository and push to destination repository
          git fetch origin main:source-main
          git push origin source-main:destination-branch

          cd ..

