name: Mirror Repository

on:
  push:
    branches:
      - main  

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          repository: ghost8658private/ttesting  # Change this to the source repository
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Mirror to Target Repository  
        run: |
          git config --global user.name "ghost8658private"
          git config --global user.email "bbbeeeaaabbb9@gmail.com"
          git clone https://github.com/ghost8658private/trtos.git mirror
          cd mirror
          git checkout -b main
          git push origin main
        
