name: Mirror Branch

on:
  push:
    branches:
      - power

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: 'ghost8658private/devopsworkflows'
          source_branch: 'power'
          destination_branch: 'power'
          github_token: ${{ secrets.PAT_TOKEN }}