name: Create and Clone Branch

on:
  push:
    branches:
      - power  

jobs:
  create-and-clone:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "ghost8658"
        git config --global user.email "ghost8658@gmail.com"
        git config --global credential.helper store
    
    - name: Create new branch
      run: |
        git checkout -b new-branch
        git push --set-upstream new-branch
        
    - name: Clone source repository
      run: |
        git clone https://github.com/ghost8658private/devopsworkflows.git
        cd devopsworkflows
        git checkout main  # Replace 'main' with the branch you want to clone
        
        # Copy the contents of the source repository into the new branch
        cp -R * ../
        cd ..
        
        # Commit and push changes to the new branch
        git add .
        git commit -m "Clone source repo into new-branch"
        git push origin new-branch
