name: Create and Clone Branch

on:
  push:
    branches:
      - power  

jobs:
  create-and-clone:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global credential.helper store
    
    - name: Create new branch
      run: |
        git checkout -b new-branch
        git push --set-upstream origin new-branch
        
    - name: Clone source repository
      run: |
        git clone https://github.com/ghost8658private/devopsworkflows.git
        git remote remove origin
        git remote add origin https://github.com/ghost8658private/ttesting.git
        
        
        #cd devopsworkflows
        #git checkout main  # Replace 'main' with the branch you want to clone
        echo "new fish" > cat.txt
        # Copy the contents of the source repository into the new branch
        # cp -R  ./* ../
        # cd ..
        
        # Commit and push changes to the new branch
        git add .
        git commit -m "Clone source repo into new-branch"
        
        
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.PAT_TOKEN }}
        branch: new-branch
    
