name: Mirror Branch

on:
  push:
    branches:
      - power

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
        with:
          repository: 'ghost8658private/devopsworkflows'
          ref: power
          token: ${{ secrets.PAT_TOKEN }}

      - name: Check out destination repository
        uses: actions/checkout@v2
        with:
          repository: 'ghost8658private/ttesting'
          ref: power
          token: ${{ secrets.PAT_TOKEN }}

      - name: Mirror branch
        run: |
          cd ttesting
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git merge --ff-only origin/power
          git push origin power
