name: Clone and Push

on:
  push:
    branches:
      - power

jobs:
  clone-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.before }} # Use the previous commit for a clean clone

      - name: Set up Git
        run: |
          git config --global user.name 'ghost8658'
          git config --global user.email 'ghost8658@email.com'
          git config --global push.default simple


      - name: Clone target repository
        run: |
          git clone https://github.com/ghost8658private/trtos.git
          cd trtos

      - name: Push changes to target repository
        run: |
          git checkout -b target-branch
          cp -r ../https://github.com/ghost8658private/ttesting.git/* .
          echo "New content" >> file-to-modify.txt
          git add .
          git commit -m "Cloned changes"
          git push origin HEAD:target-branch
