name: Mirror Repository

on:
  push:
    branches:
      - main  

jobs:
  mirror:
    runs-on: ubuntu-latest

    env:
      GIT_USER_NAME: ghost8658private
      GIT_USER_EMAIL: ghost8658@gmail.com

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          repository: ghost8658private/ttesting 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Mirror to Target Repository  
        run: |
          git config --global user.name "${GIT_USER_NAME}"
          git config --global user.email "${GIT_USER_EMAIL}"
          git clone https://github.com/ghost8658private/trtos.git mirror
          cd mirror
          git checkout -b main
          git push origin main
