name: Mirror to public

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  workflow_dispatch:

jobs:
  call_mirror_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v2  # You can use a specific version here if needed
        with:
          repository: ghost8658private/ttesting
          ref: main
          token: ${{ secrets.PAT_TOKEN }}
          subdirectory: .github/workflows

      - name: Run Mirror Workflow in Target Repo
        uses: actions/github-script@v5
        with:
          script: |
            const token = process.env.PAT_TOKEN;
            const octokit = new Octokit({ auth: token });
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            const workflow_id = 'copy.yml';  # Adjust to the actual workflow file name
            
            await octokit.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id,
              ref: 'main',  # Replace with the desired branch
              inputs: {
                source-branch: 'mainn',  # Replace with the desired source branch
                target-repo-name: 'trtos',
                target-repo-url: 'https://github.com/ghost8658private/trtos.git',  # Missing comma here
                base-branch: 'tmo-main',
                source-repo-name: 'ttesting'
              }
            });
