name: Mirror Branch

on:
  push:
    branches:
      - newpower

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: 'ghost8658private/ttesting'
          source_branch: 'power'
          target_repo: 'ghost8658private/fourth'
          target_branch: 'power'
          github_token: ${{ secrets.PAT_TOKEN }}
