name: First mirror from tclone to rtos work

on:
  workflow_call:
    inputs:
      source-repo:
        required: true
        type: string
      target-repo:
        required: true
        type: string
      source-repo-name:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  synchronize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    

      - name: Set Git Credentials
        run: |
          git config --global user.email "bbbeeeaaabbb9@gmail.com"
          git config --global user.name "ghost8658private"


      - name: Clone source repository
        run: git clone https://${{ secrets.ACCESS_TOKEN }}@${{ inputs.source-repo }} --depth 1 source-repo
      
      - name: Clone target repository
        run: git clone https://${{ secrets.ACCESS_TOKEN }}@${{ inputs.target-repo }} --depth 1 target-repo
  
      - name: Merge source to target
        run: |
          cd target-repo
          git remote add source-repo ${{ inputs.source-repo }}
          git fetch source-repo
          git merge --no-commit --allow-unrelated-histories source-repo/main
          git commit -m "Merge ${inputs.source-repo-name} repository to target"
          git push